### ISSUE TITLE
Hawkey is deprecated, use libhif instead

### ISSUE THREAD

**Issue by genodeftest** [manatools/dnfdaemon#4]
See [these announcements](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/FTQ4PFFTCP36AMWQXFZEYMXBDILIL5EY/) [[2](http://dnf.baseurl.org/2016/02/24/dnf-into-c-initiative-started/)] for details.

**Comment by timlau** [comment]
should be good for now

* python bindings will not change and the libhif package will still provide `python2-hawkey` and `python3-hawkey`

**Comment by Conan-Kudo** [comment]
For the time being, we're continuing to use the Hawkey Python API provided by libdnf.
