### ISSUE TITLE
Locking doesn't work as expected, Exception handling too

### ISSUE THREAD

**Issue by genodeftest** [manatools/dnfdaemon#5]
While experimenting with `yumex-dnf/src/yumex/updater.py`, in `Updater.get_updates()`, I changed these lines:

```
        try:
            self.backend.Lock()
            pkgs = self.backend.GetPackages('updates')
            rc = len(pkgs)
            logger.debug('# of updates : %d' % rc)
            self.backend.Unlock()
        except:  # Get locking errors
            logger.debug('Error getting the dnfdaemon lock')
            rc = -1
```

I wanted to make the `except:` statement less general and only capture `dnfdaemon.client.LockedError`, but this failed for two reasons:
1. Running `self.backend.Lock()` is executed without exceptions although yumex-dnf is still running and keeping the lock.
2. Running `self.backend.GetPackages('updates')` triggers an Exception, but due to `dnfdaemon.client.DnfDaemonBase._handle_dbus_error()` directly parsing strings, the string `g-io-error-quark: GDBus.Error:org.baseurl.DnfSystem.LockedError: dnf is locked by another application (36)` is incorrectly handed and not recognized as `dnfdaemon.client.LockedError`.

It seems like `dnfdaemon.client.DnfDaemonBase._handle_dbus_error()` is supposed to handle both client and server side errors, but I think they should be handled separately.

**Comment by timlau** [comment]
Looks like the code is broken.
self.backend.Lock() returns True is the lock is acuired and False is the daemon is already locked.

The code should proberly be like this
```python
        logger.debug('Checking for updates')
        try:
            if self.backend.Lock():
                pkgs = self.backend.GetPackages('updates')
                rc = len(pkgs)
                logger.debug('# of updates : %d' % rc)
                self.backend.Unlock()
            else:
                logger.debug('Error getting the dnfdaemon lock')
                rc = -1
        except:  # catch backend exception
            logger.debug('Error in getting updates')
            rc = -1
```

**Comment by timlau** [comment]
LockedError is only raised if you call a dbus method and dont have the lock

**Comment by timlau** [comment]
https://github.com/timlau/yumex-dnf/commit/d8154909c3407d27ef5433bc15c394111c1ab8e2

**Comment by genodeftest** [comment]
Your commit fixes the locking for me. Thanks!

**Comment by Conan-Kudo** [comment]
This looks fixed. Closing.
